rawdata<-read.table("household_power_consumption.txt",header=TRUE,sep=";",na.strings="?",as.is=TRUE)
rawdata<-subset(rawdata,Date=="1/2/2007"|Date=="2/2/2007")
x_axs_value<-strptime(paste(rawdata$Date,rawdata$Time),"%d/%m/%Y %H:%M:%S")
png(filename="plot2.png",width=480,height=480)
plot(x_axs_value,rawdata$Global_active_power,type="l",ylab="Global Active Power (kilowatts)",xaxt="n",xlab="")
x_axs_day<-format(seq.Date(as.Date('2007-02-01'), by = 'day', len=3),"%Y-%m-%d")
x_axs_at<-paste(x_axs_day,"00:00:00")
x_axs<-as.numeric(strptime(x_axs_at, "%Y-%m-%d %H:%M:%S"))
axis(side=1,at=c(x_axs),labels=c("Thu","Fri","Sat"))
dev.off()